### ISSUE TITLE
data folder

### ISSUE THREAD

**Issue by ntienvu** [larsroemheld/causalinf_ex_elasticity#1]
The project looks very interesting. Thanks for sharing. That would be excellent if you can share the data folder as well (or a link to the data folder) ? Regards, Vu

**Comment by larsroemheld** [comment]
You can find a link and the data preparation pipeline in `[data_prep.ipynb](https://github.com/larsroemheld/causalinf_ex_elasticity/blob/main/data_prep.ipynb)`
